let num1 = 20;
let num2 = 15;
let pow = Math.pow(num1,num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
console.log(num1 === num2);
console.log(num1 == num2);
console.log(num1 !== num2);
console.log(num1 != num2);
console.log(pow);